# -*- coding: utf-8 -*-
"""multi_linear_regression_to_predict_i10_index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oed6Gf9Qi_D5OHpzBEGA4eLQ8hmmm1CX
"""

import joblib
import seaborn as sns
import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data=pd.read_excel('aggregate_professor_data_hm.xlsx')

data['I10-index'].fillna(0,inplace=True)
data.describe()

data.info()

numericals_df=data.drop(columns='Professor Name',axis=1)
numericals_df.corr()

pairplot=sns.pairplot(numericals_df)
pairplot.savefig('pairplot.png')

files.download('pairplot.png')

plt.figure(figsize=(10, 6))
heatmap = sns.heatmap(numericals_df.corr(), annot=True, cmap="inferno_r", fmt=".2f")
plt.title("Correlation Heatmap")
plt.savefig('heatmap.png', dpi=300, bbox_inches='tight')
files.download('heatmap.png')

"""MULTILINEAR REGRESSION MODEL FOR PREDICTING I10 INDEX USING TOTAL CITATION, TOTAL PUBLICATION, H-INDEX"""

#data cleaning
df_clean=data[data['I10-index']>0]#removing the null values
df_clean.head()

X=df_clean[["Total Publications","Total Citations","H-index"]]
Y=df_clean['I10-index']
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

model =LinearRegression()
model.fit(X_train,Y_train)

#output
y_predicted=model.predict(X_test)
mse=mean_squared_error(Y_test,y_predicted)
r2=r2_score(Y_test,y_predicted)
y_train_predicted=model.predict(X_train)
mse_train=mean_squared_error(Y_train,y_train_predicted)
r2_train=r2_score(Y_train,y_train_predicted)
print(f"Mean Squared Error [Train]: {mse_train}")
print(f"R-squared [Train]: {r2_train}")
print(f"Mean Squared Error [Test]: {mse}")
print(f"R-squared [Test]: {r2}")

plt.subplot(1, 2, 2)
plt.scatter(Y_test, y_predicted, color="green")
plt.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()], color="red", linestyle="--")
plt.title("Testing Set: Actual vs Predicted")
plt.xlabel("Actual I10-index")
plt.ylabel("Predicted I10-index")
plt.savefig('scatterplot.png')
files.download('scatterplot.png')

print("predicted: ",y_predicted)
print("actial: ", Y_test)

"""ILINEAR REGRESSION MODEL FOR PREDICTING I10 INDEX USING TOTAL CITATION, TOTAL PUBLICATION, H-INDEX"""

X2=df_clean[["H-index"]]
Y2=df_clean['I10-index']
X2_train,X2_test,Y2_train,Y2_test=train_test_split(X2,Y2,test_size=0.3,random_state=42)
model2=LinearRegression()
model2.fit(X2_train,Y2_train)

y2_predicted=model2.predict(X2_test)
mse2=mean_squared_error(Y2_test,y2_predicted)
r22=r2_score(Y2_test,y2_predicted)
print(f"Mean Squared Error: {mse2}")
print(f"R-squared: {r22}")

plt.subplot(1, 2, 2)
plt.scatter(Y2_test, y2_predicted, color="green")
plt.plot([Y2_test.min(), Y2_test.max()], [Y2_test.min(), Y2_test.max()], color="red", linestyle="--")
plt.title("Testing Set: Actual vs Predicted")
plt.xlabel("Actual I10-index")
plt.ylabel("Predicted I10-index")
plt.savefig('scatterplot2.png')
files.download('scatterplot2.png')

print("predicted: ",y2_predicted)
print("actial: ", Y2_test)

"""UPDATING THR VALUES OF THE DATA WITH THE PREDICTED VALUES"""

rows_with_i10_zero=data[data['I10-index']==0]
x_to_predict=rows_with_i10_zero[["Total Publications","Total Citations","H-index"]]
predicted_values=model.predict(x_to_predict)
data.loc[data['I10-index']==0,'I10-index']=predicted_values
data.to_excel('aggregate_professor_data_with_predicted_i10.xlsx',index=False)
files.download('aggregate_professor_data_with_predicted_i10.xlsx')

joblib.dump(model, 'multi_linear_regression_i10_predictor.pkl')
files.download('multi_linear_regression_i10_predictor.pkl')